# -*- coding: utf-8 -*-
"""Assignment_D41_Streamlit_IndraLaksana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jaqZBZBXdxWTX0FuRcDWIWUoXGmtnZU
"""

!pip install streamlit
!npm install -g localtunnel
!pip install pyngrok streamlit -q

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # --- Load dataset ---
# df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Day-41 Streamlit/Sample - Superstore.csv", encoding="latin1")
# 
# # --- Sidebar ---
# st.sidebar.title("My Profil")
# st.sidebar.write("**Nama:** Indra Laksana")
# st.sidebar.write("**Role:** Aspiring Data Analyst")
# st.sidebar.write("**Email:** laksanaindra27@gmail.com")
# st.sidebar.write("**LinkedIn:** [www.linkedin.com/in/laksana-indra/](https://www.linkedin.com/in/laksana-indra/)")
# st.sidebar.write("**GitHub:** [https://github.com/laksanaindra](https://github.com/laksanaindra)")
# 
# st.title("📊 Dashboard Analisis Superstore")
# 
# # --- Tren Penjualan per Bulan ---
# st.header("📈 Tren Penjualan per Bulan")
# df['Order Date'] = pd.to_datetime(df['Order Date'])
# monthly_sales = df.groupby(df['Order Date'].dt.to_period("M"))['Sales'].sum().reset_index()
# monthly_sales['Order Date'] = monthly_sales['Order Date'].dt.to_timestamp()
# 
# fig1 = px.line(monthly_sales, x="Order Date", y="Sales",
#                title="Tren Penjualan per Bulan", markers=True)
# st.plotly_chart(fig1, use_container_width=True)
# st.write("**Insight:** Penjualan meningkat menjelang akhir tahun, menunjukkan pola musiman.")
# 
# # --- Penjualan & Profit per Kategori ---
# st.header("Penjualan & Profit per Kategori")
# category_sales = df.groupby('Category')[['Sales','Profit']].sum().reset_index()
# 
# fig2 = px.bar(category_sales, x="Category", y=["Sales","Profit"],
#               barmode="group", title="Penjualan & Profit per Kategori")
# st.plotly_chart(fig2, use_container_width=True)
# st.write(" **Insight:** Office Supplies punya penjualan tinggi, tapi Furniture profitnya lebih rendah.")
# 
# # --- Distribusi Penjualan per Region ---
# st.header("Distribusi Penjualan per Region")
# region_sales = df.groupby('Region')['Sales'].sum().reset_index()
# 
# fig3 = px.bar(region_sales, x="Region", y="Sales",
#               title="Distribusi Penjualan per Region", text_auto=True)
# st.plotly_chart(fig3, use_container_width=True)
# st.write("**Insight:** Region West menyumbang penjualan terbesar di dataset.")
# 
# # --- Top 10 Produk dengan Penjualan Tertinggi ---
# st.header("Top 10 Produk dengan Penjualan Tertinggi")
# top_products = df.groupby("Product Name")["Sales"].sum().nlargest(10).reset_index()
# 
# fig4 = px.bar(top_products, x="Sales", y="Product Name",
#               orientation="h", title="Top 10 Produk dengan Penjualan Tertinggi")
# st.plotly_chart(fig4, use_container_width=True)
# st.write("**Insight:** Produk tertentu sangat mendominasi revenue, penting untuk fokus menjaga ketersediaannya.")
# 
# # --- Segmentasi Customer ---
# st.header(" Segmentasi Customer")
# segment_sales = df.groupby("Segment")["Sales"].sum().reset_index()
# 
# fig5 = px.pie(segment_sales, names="Segment", values="Sales",
#               title="Proporsi Penjualan per Segment Customer")
# st.plotly_chart(fig5, use_container_width=True)
# st.write("**Insight:** Konsumen (Consumer) menyumbang bagian terbesar, menunjukkan pentingnya fokus pada segmen ini.")
# 
# # --- Profit per State (Map) ---
# st.header(" Profit per State")
# state_profit = df.groupby("State")["Profit"].sum().reset_index()
# 
# fig6 = px.choropleth(state_profit,
#                      locations="State",
#                      locationmode="USA-states",
#                      color="Profit",
#                      scope="usa",
#                      title="Profit per State (USA)")
# st.plotly_chart(fig6, use_container_width=True)
# st.write("**Insight:** Profit sangat bervariasi antar state; ada beberapa state dengan kerugian signifikan yang perlu dianalisis lebih lanjut.")
#

!streamlit run app.py --server.port 8501 &>/content/logs.txt &

from pyngrok import ngrok
public_url = ngrok.connect(8501)
print("🌍 URL Streamlit kamu:", public_url)